routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', [\App\Http\Controllers\LandingpageController::class, 'index']);

Route::get('/login', [\App\Http\Controllers\AuthController::class, 'index'])->name('login');
Route::post('/cek-login', [\App\Http\Controllers\AuthController::class, 'login'])->name('login-cek');
Route::get('/logout', [\App\Http\Controllers\AuthController::class, 'logout'])->name('logout');

Route::group(['middleware' => 'auth'], function () {
   Route::get('/home', [\App\Http\Controllers\DashboardController::class, 'index'])->name('home');

   Route::resource('user', \App\Http\Controllers\UserController::class);
   Route::resource('post', \App\Http\Controllers\PostController::class);
});

app/Models/Post.php
<?php

namespace App\Models;

use App\Traits\WithPictures;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use WithPictures;

    protected $fillable = [
        'tittle',
        'description',
        'slug',
        'user_id',
        'is_display'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class PostController extends Controller
{
    public function __construct()
    {
        $this->tittle = 'Post';
    }

    public function index(Request $request)
    {
        $posts = Post::all();
        $tittle = $this->tittle;

        return view('post/index', compact('posts', 'tittle'));
    }

    public function create()
    {
        $tittle = $this->tittle;

        return view('post/create', compact('tittle'));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            // Tambahkan aturan validasi untuk file gambar di sini sesuai kebutuhan Anda
            'images' => 'image|mimes:jpeg,png,jpg,gif|max:2048',
        ]);

        if ($validator->fails()) {dd($validator);
            return redirect()->back()->withErrors($validator)->withInput();
        }

        try {
            DB::beginTransaction();

            $request->merge([
               'slug' => $this->generateSlug($request->tittle)
            ]);

            $post = Post::create($request->all());
//            dd($request);
            if ($request->hasFile('images')) {
                    insert_picture($request->images, $post);
            }
//            dd($post->picture);
            DB::commit();
            return redirect()->route('post.index')->with('Data berhasil ditambah!');
        } catch (\Exception $exception) {
//            DB::rollBack();
            dd($exception);
            return redirect()->route('post.index')->with($exception->getMessage());
        }
    }

    public function show(Post $post)
    {dd($post->picture->url);
        $tittle = $this->tittle;

        return view('post/show', compact('post', 'tittle'));
    }

    private function generateSlug($title)
    {
        $slug = strtolower(str_replace(' ', '-', $title));

        $slug = preg_replace('/[^a-z0-9\-]/', '', $slug);

        $slug = preg_replace('/-+/', '-', $slug);

        if (empty($slug)) {
            $slug = 'untitled';
        }

        return $slug;
    }
}

resources/views/post/create.blade.php
@extends('layout.app')

@push('css')
    <style>
        #image-preview {
            display: flex;
            flex-wrap: wrap;
        }

        .img-thumbnail {
            margin: 20px;
            border: 2px solid #ccc;
            border-radius: 5px;
            padding: 5px;
        }
    </style>

@endpush

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">{{$tittle}}</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">{{$tittle}}</a></li>
                    <li class="breadcrumb-item active">Create</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <!-- Main row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Fom {{$tittle}}</h5>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('post.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="tittle">Judul Artikel</label>
                                        <input type="text" name="tittle" value="{{ old('tittle') }}" class="form-control @error('tittle') is-invalid @enderror" id="tittle" placeholder="Isi Judul">
                                        @error('tittle')
                                        <span class="invalid-feedback">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="description">Deskripsi</label>
                                        <textarea id="summernote" name="description">{{ old('description') }}</textarea>
                                        @error('description')
                                        <span class="invalid-feedback">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label for="description">Gambar</label>
                                        <input type="file" name="images" id="images" multiple accept="image/jpeg, image/png, image/jpg, image/gif">
                                        <div id="image-preview" class="mt-2"></div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <a href="{{ route('post.index') }}" class="btn btn-danger"><i class="fas fa-chevron-left"></i> Kembali</a>
                                    <button class="btn btn-success"><i class="fas fa-save"></i> Simpan</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
@endsection

@push('js')
    <script>
        document.getElementById('images').addEventListener('change', function() {
            var imagePreview = document.getElementById('image-preview');
            imagePreview.innerHTML = ''; // Bersihkan tampilan preview sebelumnya

            for (var i = 0; i < this.files.length; i++) {
                var file = this.files[i];
                if (file.type.match('image.*')) {
                    var reader = new FileReader();

                    reader.onload = function(e) {
                        var img = document.createElement('img');
                        img.className = 'img-thumbnail m-2'; // Ganti sesuai kebutuhan
                        img.style.maxWidth = '150px'; // Ganti sesuai kebutuhan
                        img.src = e.target.result;
                        imagePreview.appendChild(img);
                    };

                    reader.readAsDataURL(file);
                }
            }
        });
    </script>
@endpush

resources/views/post/edit.blade.php
@extends('layout.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">User</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">User</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <!-- Main row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h5>Fom User</h5>
                        </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('user.update', $user->id) }}">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="name">Nama</label>
                                            <input type="text" name="name" value="{{ $user->name }}" class="form-control @error('name') is-invalid @enderror" id="name">
                                            @error('name')
                                            <span class="invalid-feedback">{{ $message }}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="email">Email</label>
                                            <input type="email" name="email" value="{{ $user->email }}" class="form-control @error('email') is-invalid @enderror" id="email">
                                            @error('email')
                                            <span class="invalid-feedback">{{ $message }}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="username">Username</label>
                                            <input type="text" name="username" value="{{ $user->username }}" class="form-control @error('username') is-invalid @enderror" id="username">
                                            @error('username')
                                            <span class="invalid-feedback">{{ $message }}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="role">Role</label>
                                            <select class="form-control" name="role" id="role">
                                                <option value="">Pilih Role</option>
                                                <option value="admin" @if ($user->role == "admin") {{ 'selected' }} @endif>Admin</option>
                                                <option value="user" @if ($user->role == "user") {{ 'selected' }} @endif>User</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="id_bidang">Bidang</label>
                                            <select class="form-control" name="id_bidang" id="id_bidang">
                                                <option value="">Pilih Bidang</option>
                                                @foreach($bidang as $data)
                                                    <option value="{{ $data->id }}" @if ($user->id_bidang == $data->id) {{ 'selected' }} @endif>{{ $data->nama_bidang }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="password">Password</label>
                                            <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" autocomplete="current-password">
                                            @error('password')
                                            <span class="invalid-feedback">{{ $message }}</span>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="password">Konfirmasi Password</label>
                                            <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password_confirmation" autocomplete="current-password">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <a href="{{ route('user.index') }}" class="btn btn-danger"><i class="fas fa-chevron-left"></i> Kembali</a>
                                        <button class="btn btn-success"><i class="fas fa-save"></i> Simpan</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
@endsection

@push('css')
<link rel="stylesheet" href="{{ asset('adminlte') }}/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
@endpush

@push('js')
<script src="{{ asset('adminlte') }}/plugins/select2/js/select2.full.min.js"></script>

<script>
    $(document).ready(function(){
        $('#role').select2({
            theme: 'bootstrap4',
            placeholder: 'Pilih Role'
        })
        $('#id_bidang').select2({
            theme: 'bootstrap4',
            placeholder: 'Pilih Bidang'
        })
    })
</script>
@endpush

resources/views/post/index.blade.php
@extends('layout.app')

@section('content')

@push('css')
    <!-- datatable -->
@endpush

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">{{ $tittle }}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{ $tittle }}</a></li>
                        <li class="breadcrumb-item active">Index</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <!-- Small boxes (Stat box) -->
            <!-- Main row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <a href="{{ route('post.create') }}" class="btn btn-success"><i class="fas fa-plus"></i> Tambah Data : {{$tittle}}</a>
                        </div>
                        <div class="card-body">
                            @include('partials.message')
                            <table class="table table-striped table-bordered" id="dt_table">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Judul</th>
                                    <th>Slug</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($posts as $post)
                                    <tr>
                                        <td>{{$loop->iteration}}</td>
                                        <td>{{ $post->tittle }}</td>
                                        <td>{{ $post->slug }}</td>
                                        <td>{{ $post->status }}</td>
                                        <td>
                                            <form action="{{ route('post.destroy', $post) }}" method="POST">
                                                <a href="{{ route('post.show', $post) }}" class="btn btn-success btn-sm">Show</a>
                                                <a href="{{ route('post.edit', $post) }}" class="btn btn-warning btn-sm">Edit</a>
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
@endsection

@push('js')
    <script>
        $(document).ready(function(){
            var dt = $('#dt_table').DataTable({
                autoWidth: false,
                searching: true,
                responsive: true,
            });

            dt.on('order.dt search.dt', function () {
                let i = 1;

                dt.cells(null, 0, { search: 'applied', order: 'applied' }).every(function (cell) {
                    this.data(i++);
                });
            }).draw();
        })
    </script>
@endpush

resources/views/post/show.blade.php
@extends('layout.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">User</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">User</a></li>
                    <li class="breadcrumb-item active">Show</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <!-- Main row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Fom User</h5>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label for="name">Nama</label>
                                    <input type="text" name="name" value="{{ $user->name }}" class="form-control @error('name') is-invalid @enderror" id="name" readonly>
                                    @error('name')
                                    <span class="invalid-feedback">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="email" name="email" value="{{ $user->email }}" class="form-control @error('email') is-invalid @enderror" id="email" readonly>
                                    @error('email')
                                    <span class="invalid-feedback">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    <input type="text" name="username" value="{{ $user->username }}" class="form-control @error('username') is-invalid @enderror" id="username" readonly>
                                    @error('username')
                                    <span class="invalid-feedback">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label for="role">Role</label>
                                    <select class="form-control" name="role" id="role" disabled>
                                        <option value="">Pilih Role</option>
                                        <option value="admin" @if ($user->role == "admin") {{ 'selected' }} @endif>Admin</option>
                                        <option value="user" @if ($user->role == "user") {{ 'selected' }} @endif>User</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label for="id_bidang">Bidang</label>
                                    <select class="form-control" name="id_bidang" id="id_bidang" disabled>
                                        <option value="">Pilih Bidang</option>
                                        @foreach(\App\Models\Bidang::all() as $data)
                                            <option value="{{ $data->id }}" @if ($user->id_bidang == $data->id) {{ 'selected' }} @endif>{{ $data->nama_bidang }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <a href="{{ route('user.index') }}" class="btn btn-danger"><i class="fas fa-chevron-left"></i> Kembali</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
@endsection